name: Release
on:
  release: {}
  push:
    tags: ['*']

jobs:
  "Wait":
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        if:   ${{ !env.ACT }}
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'Test'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  "Changelog":
    runs-on: ubuntu-latest
    needs: ["Wait"]
    steps:
      - name: Check out sources
        uses: actions/checkout@v3
      - name: Generate changelog
        run:  bash "${{ github.workspace }}/.github/actions/build/create-changelog.sh"

  "Package":
    runs-on: ubuntu-latest
    needs: ["Wait"]
    steps:
      - name: Check out sources
        uses: actions/checkout@v3
      - name: Generate changelog
        run:  bash "${{ github.workspace }}/.github/actions/build/create-changelog.sh"
